# Azure Pipeline for Automated Report Generation
# This pipeline automatically runs report generation scripts and commits the results to the repository
# Scheduled to run daily to keep reports up-to-date

trigger: none  # Only run on schedule, not on commits

schedules:
- cron: "0 2 * * *"  # Run daily at 2:00 AM UTC
  displayName: 'Daily report generation'
  branches:
    include:
    - main
  always: true

variables:
  - group: 'sonarqube-config'  # Variable group containing SonarQube URL and token
  - name: reportDirectory
    value: 'reports'
  - name: vmImageName
    value: 'windows-latest'

pool:
  vmImage: $(vmImageName)

stages:
- stage: GenerateReports
  displayName: 'Generate and Commit Reports'
  jobs:
  - job: SonarQubeReports
    displayName: 'Generate SonarQube Reports'
    steps:
    
    - checkout: self
      persistCredentials: true
      displayName: 'Checkout repository with credentials'
    
    - task: PowerShell@2
      displayName: 'Configure Git for automated commits'
      inputs:
        targetType: 'inline'
        script: |
          git config --global user.email "azure-pipeline@devops.com"
          git config --global user.name "Azure Pipeline Bot"
          Write-Host "Git configured for automated commits"
    
    - task: PowerShell@2
      displayName: 'Create reports directory'
      inputs:
        targetType: 'inline'
        script: |
          $reportDir = "$(Build.SourcesDirectory)/$(reportDirectory)"
          if (-not (Test-Path $reportDir)) {
            New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
            Write-Host "Created reports directory: $reportDir"
          } else {
            Write-Host "Reports directory already exists: $reportDir"
          }
    
    - task: PowerShell@2
      displayName: 'Generate SonarQube Project Report'
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/scripts/powershell/Get-SonarQubeProjectInfo.ps1'
        arguments: '-SonarQubeUrl "$(SONARQUBE_URL)" -Token "$(SONARQUBE_TOKEN)" -OutputPath "$(Build.SourcesDirectory)/$(reportDirectory)/sonarqube-projects-report.md"'
        errorActionPreference: 'continue'
        failOnStderr: false
      continueOnError: true
      env:
        SONARQUBE_URL: $(SONARQUBE_URL)
        SONARQUBE_TOKEN: $(SONARQUBE_TOKEN)
    
    - task: PowerShell@2
      displayName: 'Check for changes and commit'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Checking for changes in reports directory..."
          
          # Check if there are any changes
          git status --porcelain
          
          $changes = git status --porcelain
          if ($changes) {
            Write-Host "Changes detected in reports. Committing changes..."
            
            # Add report files
            git add $(reportDirectory)/*.md
            
            # Create commit message with timestamp
            $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
            $commitMessage = "chore: automated report generation - $timestamp [skip ci]"
            
            git commit -m "$commitMessage"
            
            # Push changes to main branch
            Write-Host "Pushing changes to main branch..."
            git push origin HEAD:main
            
            Write-Host "Reports committed and pushed successfully"
          } else {
            Write-Host "No changes detected in reports directory"
          }
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    
    - task: PowerShell@2
      displayName: 'Cleanup old log files'
      inputs:
        targetType: 'inline'
        script: |
          # Remove PowerShell transcript logs generated by the report script
          Get-ChildItem -Path "$(Build.SourcesDirectory)" -Filter "sonarqube-script-*.log" -ErrorAction SilentlyContinue | Remove-Item -Force
          Write-Host "Cleaned up old log files"
      condition: always()
